### ISSUE TITLE
Добавить issues

### ISSUE THREAD

**Issue by ademaro** [rikkihime/Portfolio#1]
Почему пусто? Где всё?)

**Comment by rikkihime** [comment]
Проверяй :)

**Comment by ademaro** [comment]
Это всё? Только 3 пунктика и можем выкладывать?

**Comment by rikkihime** [comment]
А в каждом пунктике подпунктики =) . Думаю, эти 3 пункта можно считать основой. Т.е. без них нельзя никак выкладывать. А дальше уже каркас готов будет и его уже как-то улучшать / изменять по мере появления идей... М?

**Comment by ademaro** [comment]
:ok_hand:
